# Generated by Django 5.2 on 2025-05-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacherstudent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBadge',
            new_name='ProfileBadge',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
