# Generated by Django 5.2 on 2025-06-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_knowledgebasearticle_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebasearticle',
            name='tag',
            field=models.CharField(max_length=56),
        ),
    ]
