# Generated by Django 5.2 on 2025-06-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_knowledgebasearticle_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdeliverableprogress',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
