# Generated by Django 5.2 on 2025-06-04 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_evaluation_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='coach',
        ),
        migrations.CreateModel(
            name='CoachStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coachprofile')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.studentprofile')),
            ],
            options={
                'unique_together': {('coach', 'student')},
            },
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='students',
            field=models.ManyToManyField(related_name='coaches', through='core.CoachStudent', to='core.studentprofile'),
        ),
    ]
