name: Deployment to VPS

on:
  push:
    branches: [ implementation/github-actions ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          pwd
          cd mysite
          python manage.py test


      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: 🚀 Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ${{ secrets.PROJECT_DIR }}

            echo "Pulling latest code..."
            git pull origin main

            echo "Building backend Docker image..."
            docker build -t django-app ./backend

            echo "Building frontend Docker image..."
            docker build -t react-app ./frontend

            echo "Stopping old containers..."
            docker stop django-container || true && docker rm backend || true
            docker stop react-container || true && docker rm frontend || true

            echo "Running backend container..."
            docker run -d --name django-container --env-file ./backend/mysite/.env -p 8000:8000 django-app

            echo "Running frontend container..."
            docker run -d -p 3001:80 --name react-container --env-file ./frontend/.env react-app

            echo "Restarting NGINX..."
            sudo systemctl restart nginx
          EOF
